### PR TITLE
I3s task and job

### PR DESCRIPTION
**Pull request by mbfrahry**
The format for this is similar to the other resources so I added the basic methods and testing but I won't know if it works until we get access to i3s. Let me know if this isn't a good idea @wenlock.
Signed-off-by: matthew-frahry <matthew.frahry@hpe.com>

### CODE REVIEW

**Comment by wenlock** [comment]
@mbfrahry looks really good.    If you could get the unit test to pass, then we can get this merged so we can do acceptance testing on it once we have our env up.

**Comment by mbfrahry** [comment]
Haha I'm working on it! The more I add, the more stuff breaks! I'll get it!

**Comment by wenlock** [comment]
hehe yep, lets add some baby chunks at a time.  This is probably enough resources for this PR before we add the next set.

**Comment by mbfrahry** [comment]
@wenlock, I think this is good to go.

**Pull request merged**
