### PR TITLE
add fc network resource

### PR DESCRIPTION
**Pull request by dh2mom247**
Please merge now

### CODE REVIEW

**Comment by wenlock** [comment]
@dh2mom247 this is awesome, looks great.   If you could give me a day to try it locally that would be awesome.   @mbfrahry would you mind giving this a quick look?

Thanks !

**Comment by mbfrahry** [comment]
@dh2mom247 You need to sign off on your commits. Next time run `git commit -s`. To sign off on the previous commit, you can run `git commit --ammend --signoff`

**Comment by wenlock** [comment]
@dh2mom247 this change worked good on all my local testing and I'm ready to merge it.  Can you hit the re-base button or update from master so we can merge?

**Comment by wenlock** [comment]
LGTM

**Pull request merged**
