### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mbfrahry**

### CODE REVIEW

**Comment by wenlock** [comment]
woops, thats a mistake... Will merge after ci passes, thanks!

LGTM

**Comment by mbfrahry** [comment]
Sorry! I'm seeing if the tests are working before I mess with everything

**Comment by wenlock** [comment]
ahh , cool!  you want me to leave it open?

**Comment by mbfrahry** [comment]
I'll go ahead and close it down!

**Pull request closed without merging**
